server:
  port: 8762
spring:
  application:
    name: native-config-server
  profiles:
    # 配置文件获取方式指定为native本地
    active: native
  cloud:
    config:
      server:
        native:
          # 本地配置文件存放路径
          search-locations: classpath:/shared