server:
  port: 8090
spring:
  application:
    name: zipkin-client
  sleuth:
    web:
      client:
        # 设置开启请求跟踪
        enabled: true
    sampler:
      # 设置采样比例
      probability: 1.0
  zipkin:
    base-url: http://127.0.0.1:9091/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/